import type { SpecialtyFieldDefinition, SpecialtyPathwayDefinition, SpecialtyPathwayCode } from './types';
import { withFieldGuidance } from './field-guidance';

const yesNo = [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] as const;
const field = withFieldGuidance;

export const SPECIALTY_PATHWAYS: readonly SpecialtyPathwayDefinition[] = [
  {
    code: 'haemodialysis', name: 'Haemodialysis session', departmentCodes: ['haemodialysis', 'nephrology'],
    summary: 'Chair/machine assignment, prescription, vascular-access safety, observations and outcome.',
    evidenceLabel: 'CDC dialysis bloodstream-infection core interventions',
    evidenceUrl: 'https://www.cdc.gov/dialysis-safety/hcp/clinical-safety/index.html',
    safetyNote: 'A local renal lead must approve the prescription fields, escalation rules and connection/disconnection checklist before activation.',
    fields: [
      field({ key: 'modality', label: 'Modality', kind: 'select', section: 'Plan', requiredToComplete: true, options: [{ value: 'haemodialysis', label: 'Haemodialysis' }, { value: 'peritoneal_dialysis', label: 'Peritoneal dialysis' }] }),
      field({ key: 'chairId', label: 'Chair', kind: 'text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'machineId', label: 'Machine / cycler asset ID', kind: 'text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'prescriptionSummary', label: 'Signed prescription summary', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'vascularAccess', label: 'Vascular access', kind: 'select', section: 'Access & infection safety', requiredToComplete: true, options: [{ value: 'fistula', label: 'AV fistula' }, { value: 'graft', label: 'AV graft' }, { value: 'catheter', label: 'Central venous catheter' }, { value: 'pd_catheter', label: 'Peritoneal catheter' }] }),
      field({ key: 'accessAssessed', label: 'Access assessed before treatment', kind: 'boolean', section: 'Access & infection safety', requiredToComplete: true }),
      field({ key: 'handHygieneObserved', label: 'Hand hygiene performed', kind: 'boolean', section: 'Access & infection safety', requiredToComplete: true }),
      field({ key: 'asepticTechniqueObserved', label: 'Aseptic technique observed', kind: 'boolean', section: 'Access & infection safety', requiredToComplete: true }),
      field({ key: 'preWeightKg', label: 'Pre-treatment weight', kind: 'number', section: 'Observations', unit: 'kg', requiredToComplete: true, min: 0 }),
      field({ key: 'postWeightKg', label: 'Post-treatment weight', kind: 'number', section: 'Observations', unit: 'kg', requiredToComplete: true, min: 0 }),
      field({ key: 'preBloodPressure', label: 'Pre-treatment blood pressure', kind: 'text', section: 'Observations', requiredToComplete: true, help: 'Use systolic/diastolic, for example 120/80.' }),
      field({ key: 'postBloodPressure', label: 'Post-treatment blood pressure', kind: 'text', section: 'Observations', requiredToComplete: true }),
      field({ key: 'adverseEvents', label: 'Adverse events and actions', kind: 'long_text', section: 'Outcome' }),
      field({ key: 'disposition', label: 'Disposition', kind: 'select', section: 'Outcome', requiredToComplete: true, options: [{ value: 'home', label: 'Home' }, { value: 'admitted', label: 'Admitted' }, { value: 'transferred', label: 'Transferred' }, { value: 'emergency', label: 'Emergency escalation' }] }),
    ],
  },
  {
    code: 'dental', name: 'Dental assessment and treatment', departmentCodes: ['dental'],
    summary: 'Signed findings, tooth chart, treatment plan, consent and performed procedures.',
    evidenceLabel: 'ADA dental record guidance', evidenceUrl: 'https://www.ada.org/resources/practice/practice-management/writing-in-the-dental-record',
    safetyNote: 'The dental lead must approve tooth notation, procedure terminology, consent wording and local billing codes.',
    fields: [
      field({ key: 'chiefConcern', label: 'Chief concern', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'medicalHistoryReviewed', label: 'Medical history and allergies reviewed', kind: 'boolean', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'toothNotationSystem', label: 'Tooth notation', kind: 'select', section: 'Dental chart', requiredToComplete: true, options: [{ value: 'fdi', label: 'FDI two-digit' }, { value: 'universal', label: 'Universal' }, { value: 'palmer', label: 'Palmer' }] }),
      field({ key: 'toothFindings', label: 'Tooth findings', kind: 'long_text', section: 'Dental chart', requiredToComplete: true, help: 'Record tooth identifier, surface and finding.' }),
      field({ key: 'diagnosis', label: 'Diagnosis', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'treatmentPlan', label: 'Treatment plan and alternatives', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'consentRecorded', label: 'Consent / refusal recorded', kind: 'boolean', section: 'Plan', requiredToComplete: true }),
      field({ key: 'procedureCodes', label: 'Performed procedure codes', kind: 'long_text', section: 'Treatment' }),
      field({ key: 'localAnaesthetic', label: 'Local anaesthetic, dose and batch', kind: 'text', section: 'Treatment' }),
      field({ key: 'postTreatmentInstructions', label: 'Post-treatment instructions', kind: 'long_text', section: 'Outcome', requiredToComplete: true }),
    ],
  },
  {
    code: 'theatre', name: 'Operation theatre case', departmentCodes: ['operation_theatre', 'orthopaedic_surgery', 'obstetrics_gynaecology'],
    summary: 'Theatre list, consent/site, staged team pauses, anaesthesia, counts, specimens, implants and recovery.',
    evidenceLabel: 'WHO Surgical Safety Checklist', evidenceUrl: 'https://www.who.int/teams/integrated-health-services/patient-safety/research/safe-surgery/tool-and-resources',
    safetyNote: 'WHO requires local multidisciplinary adaptation and testing; these gates cannot be removed merely because local resources are constrained.',
    fields: [
      field({ key: 'procedureName', label: 'Planned procedure', kind: 'text', section: 'Case', requiredToComplete: true }),
      field({ key: 'theatreRoom', label: 'Theatre room', kind: 'text', section: 'Case', requiredToComplete: true }),
      field({ key: 'surgeon', label: 'Lead surgeon', kind: 'text', section: 'Team', requiredToComplete: true }),
      field({ key: 'anaesthesiaProvider', label: 'Anaesthesia provider', kind: 'text', section: 'Team', requiredToComplete: true }),
      field({ key: 'nursingLead', label: 'Nursing lead', kind: 'text', section: 'Team', requiredToComplete: true }),
      field({ key: 'consentAndSiteConfirmed', label: 'Consent, patient, procedure and site confirmed', kind: 'boolean', section: 'Sign in — before anaesthesia', requiredToComplete: true }),
      field({ key: 'anaesthesiaSafetyCheck', label: 'Anaesthesia safety check completed', kind: 'boolean', section: 'Sign in — before anaesthesia', requiredToComplete: true }),
      field({ key: 'pulseOximeterWorking', label: 'Pulse oximeter present and functioning', kind: 'boolean', section: 'Sign in — before anaesthesia', requiredToComplete: true }),
      field({ key: 'teamIntroduced', label: 'Team introduced by name and role', kind: 'boolean', section: 'Time out — before incision', requiredToComplete: true }),
      field({ key: 'criticalStepsDiscussed', label: 'Critical steps, risks and anticipated events discussed', kind: 'boolean', section: 'Time out — before incision', requiredToComplete: true }),
      field({ key: 'antibioticDecisionRecorded', label: 'Antibiotic prophylaxis decision recorded', kind: 'boolean', section: 'Time out — before incision', requiredToComplete: true }),
      field({ key: 'procedureAndCountsConfirmed', label: 'Procedure and instrument/swab/needle counts confirmed', kind: 'boolean', section: 'Sign out — before leaving theatre', requiredToComplete: true }),
      field({ key: 'specimensLabelled', label: 'Specimens labelled/read back or not applicable', kind: 'boolean', section: 'Sign out — before leaving theatre', requiredToComplete: true }),
      field({ key: 'recoveryConcernsDiscussed', label: 'Recovery and management concerns discussed', kind: 'boolean', section: 'Sign out — before leaving theatre', requiredToComplete: true }),
      field({ key: 'implantTraceability', label: 'Implant device, lot/serial or not applicable', kind: 'text', section: 'Traceability', requiredToComplete: true }),
      field({ key: 'anaesthesiaRecordId', label: 'Anaesthesia record ID', kind: 'text', section: 'Traceability', requiredToComplete: true }),
      field({ key: 'recoveryDisposition', label: 'Recovery disposition', kind: 'select', section: 'Outcome', requiredToComplete: true, options: [{ value: 'recovery', label: 'Recovery unit' }, { value: 'ward', label: 'Ward' }, { value: 'icu', label: 'ICU' }, { value: 'transfer', label: 'Transfer' }] }),
    ],
  },
  {
    code: 'cardiac_diagnostics', name: 'Cardiac diagnostic study', departmentCodes: ['cardiology'],
    summary: 'Order-to-acquisition-to-signed-report workflow for ECG, echo, Holter and stress testing.',
    evidenceLabel: 'HL7 FHIR DiagnosticReport', evidenceUrl: 'https://hl7.org/fhir/diagnosticreport.html',
    safetyNote: 'The cardiology lead must approve test-specific minimum datasets, acquisition roles, device interfaces and result-release policy.',
    fields: [
      field({ key: 'testType', label: 'Study', kind: 'select', section: 'Order', requiredToComplete: true, options: [{ value: 'ecg', label: '12-lead ECG' }, { value: 'echocardiogram', label: 'Echocardiogram' }, { value: 'holter', label: 'Holter monitor' }, { value: 'stress_test', label: 'Stress test' }] }),
      field({ key: 'clinicalQuestion', label: 'Clinical question / indication', kind: 'long_text', section: 'Order', requiredToComplete: true }),
      field({ key: 'deviceId', label: 'Device asset ID', kind: 'text', section: 'Acquisition', requiredToComplete: true }),
      field({ key: 'acquiredBy', label: 'Acquired by', kind: 'text', section: 'Acquisition', requiredToComplete: true }),
      field({ key: 'acquisitionQuality', label: 'Acquisition quality', kind: 'select', section: 'Acquisition', requiredToComplete: true, options: [{ value: 'diagnostic', label: 'Diagnostic' }, { value: 'limited', label: 'Limited' }, { value: 'repeat_required', label: 'Repeat required' }] }),
      field({ key: 'structuredMeasurements', label: 'Structured measurements', kind: 'long_text', section: 'Result', requiredToComplete: true }),
      field({ key: 'interpretation', label: 'Interpretation', kind: 'long_text', section: 'Result', requiredToComplete: true }),
      field({ key: 'criticalResult', label: 'Critical result', kind: 'select', section: 'Result', requiredToComplete: true, options: yesNo }),
      field({ key: 'criticalResultCommunication', label: 'Critical-result communication / not applicable', kind: 'long_text', section: 'Result', requiredToComplete: true }),
      field({ key: 'reportSignedBy', label: 'Report signed by', kind: 'text', section: 'Sign-off', requiredToComplete: true }),
    ],
  },
  {
    code: 'ophthalmology_optical', name: 'Eye exam and optical fulfilment', departmentCodes: ['ophthalmology'],
    summary: 'Structured eye examination, refraction, prescription, lens order, dispense and counselling.',
    evidenceLabel: 'HL7 FHIR VisionPrescription', evidenceUrl: 'https://hl7.org/fhir/visionprescription.html',
    safetyNote: 'Ophthalmology and optical leads must approve examination minimums, prescription authorization and stock fulfilment rules.',
    fields: [
      field({ key: 'presentingConcern', label: 'Presenting concern', kind: 'long_text', section: 'Exam', requiredToComplete: true }),
      field({ key: 'visualAcuityRight', label: 'Visual acuity — right', kind: 'text', section: 'Exam', requiredToComplete: true }),
      field({ key: 'visualAcuityLeft', label: 'Visual acuity — left', kind: 'text', section: 'Exam', requiredToComplete: true }),
      field({ key: 'iopRight', label: 'Intraocular pressure — right', kind: 'number', section: 'Exam', unit: 'mmHg', min: 0 }),
      field({ key: 'iopLeft', label: 'Intraocular pressure — left', kind: 'number', section: 'Exam', unit: 'mmHg', min: 0 }),
      field({ key: 'examFindings', label: 'Anterior/posterior segment findings', kind: 'long_text', section: 'Exam', requiredToComplete: true }),
      field({ key: 'diagnosis', label: 'Diagnosis', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'rightLens', label: 'Right lens: sphere/cylinder/axis/add/prism', kind: 'text', section: 'Prescription' }),
      field({ key: 'leftLens', label: 'Left lens: sphere/cylinder/axis/add/prism', kind: 'text', section: 'Prescription' }),
      field({ key: 'prescriber', label: 'Prescription authorized by / not applicable', kind: 'text', section: 'Prescription', requiredToComplete: true }),
      field({ key: 'fulfilmentStatus', label: 'Optical fulfilment', kind: 'select', section: 'Fulfilment', requiredToComplete: true, options: [{ value: 'not_required', label: 'Not required' }, { value: 'ordered', label: 'Ordered' }, { value: 'dispensed', label: 'Dispensed' }, { value: 'referred', label: 'Referred externally' }] }),
      field({ key: 'dispenseCounselling', label: 'Dispense counselling / not applicable', kind: 'long_text', section: 'Fulfilment', requiredToComplete: true }),
    ],
  },
  {
    code: 'mental_health', name: 'mhGAP assessment and follow-up', departmentCodes: ['psychiatry'],
    summary: 'Structured priority-condition, safety, functioning, intervention and follow-up record without replicated sensitive narrative.',
    evidenceLabel: 'WHO mhGAP Intervention Guide 2.0', evidenceUrl: 'https://www.who.int/publications/i/item/9789241549790',
    safetyNote: 'Do not enter psychotherapy or sensitive narrative here. Local confidentiality, safeguarding and break-glass policy is required for the restricted-notes store.',
    fields: [
      field({ key: 'presentingSyndrome', label: 'Priority condition / presenting syndrome', kind: 'multi_select', section: 'Assessment', requiredToComplete: true, options: [{ value: 'depression', label: 'Depression' }, { value: 'psychosis', label: 'Psychosis' }, { value: 'bipolar', label: 'Bipolar disorder' }, { value: 'epilepsy', label: 'Epilepsy/seizures' }, { value: 'substance_use', label: 'Substance use' }, { value: 'child_adolescent', label: 'Child/adolescent condition' }, { value: 'dementia', label: 'Dementia' }, { value: 'alcohol_use', label: 'Alcohol use disorder' }, { value: 'drug_use', label: 'Drug use disorder' }, { value: 'self_harm', label: 'Self-harm / suicide' }, { value: 'other_significant', label: 'Other significant mental-health complaints' }, { value: 'other', label: 'Other' }] }),
      field({ key: 'physicalCausesConsidered', label: 'Physical causes and medicines considered', kind: 'boolean', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'selfHarmRisk', label: 'Self-harm / suicide risk', kind: 'select', section: 'Safety', requiredToComplete: true, options: [{ value: 'none', label: 'None identified' }, { value: 'low', label: 'Low' }, { value: 'moderate', label: 'Moderate' }, { value: 'high_imminent', label: 'High / imminent' }] }),
      field({ key: 'violenceOrSafeguardingRisk', label: 'Violence / abuse / safeguarding risk', kind: 'select', section: 'Safety', requiredToComplete: true, options: [{ value: 'none', label: 'None identified' }, { value: 'present', label: 'Present' }, { value: 'imminent', label: 'Imminent' }] }),
      field({ key: 'safetyAction', label: 'Safety action and escalation / not applicable', kind: 'long_text', section: 'Safety', requiredToComplete: true }),
      field({ key: 'functioningImpact', label: 'Impact on daily functioning', kind: 'select', section: 'Assessment', requiredToComplete: true, options: [{ value: 'none', label: 'None' }, { value: 'mild', label: 'Mild' }, { value: 'moderate', label: 'Moderate' }, { value: 'severe', label: 'Severe' }] }),
      field({ key: 'screeningInstrumentIds', label: 'Linked screening instruments', kind: 'multi_select', section: 'Assessment', options: [{ value: 'phq9', label: 'PHQ-9' }, { value: 'gad7', label: 'GAD-7' }] }),
      field({ key: 'interventionPlan', label: 'Coded/brief intervention plan', kind: 'long_text', section: 'Plan', requiredToComplete: true, help: 'Keep this operational. Put sensitive narrative only in the restricted-note system.' }),
      field({ key: 'followUpDate', label: 'Follow-up date', kind: 'date', section: 'Follow-up', requiredToComplete: true }),
      field({ key: 'referralDisposition', label: 'Referral / disposition', kind: 'text', section: 'Follow-up', requiredToComplete: true }),
    ],
  },
  {
    code: 'dermatology', name: 'Dermatology assessment', departmentCodes: ['dermatology'],
    summary: 'Body-site findings, diagnosis, treatment and consent-governed clinical-image references.',
    evidenceLabel: 'HL7 FHIR DiagnosticReport media model', evidenceUrl: 'https://hl7.org/fhir/diagnosticreport.html',
    safetyNote: 'Images remain in the chart-document store. Local photo consent, access, retention and device-capture policy must be approved before enabling capture.',
    fields: [
      field({ key: 'history', label: 'History and symptoms', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'bodySites', label: 'Body sites', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'morphology', label: 'Morphology / examination findings', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'diagnosis', label: 'Diagnosis / differential', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'photoConsent', label: 'Clinical photography consent', kind: 'select', section: 'Images', requiredToComplete: true, options: [{ value: 'not_taken', label: 'No image taken' }, { value: 'clinical_care_only', label: 'Consented — clinical care only' }, { value: 'care_and_teaching', label: 'Consented — care and approved teaching' }, { value: 'declined', label: 'Declined' }] }),
      field({ key: 'photoDocumentIds', label: 'Chart image document IDs', kind: 'long_text', section: 'Images' }),
      field({ key: 'treatmentPlan', label: 'Treatment / procedure plan', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'followUp', label: 'Follow-up and warning signs', kind: 'long_text', section: 'Outcome', requiredToComplete: true }),
    ],
  },
  {
    code: 'physiotherapy', name: 'Physiotherapy episode', departmentCodes: ['physiotherapy'],
    summary: 'Referral, functional baseline, measurable goals, delivered session, repeated outcome and discharge.',
    evidenceLabel: 'WHO Package of Interventions for Rehabilitation', evidenceUrl: 'https://www.who.int/publications/i/item/9789240067097',
    safetyNote: 'The rehabilitation lead must select locally licensed outcome measures and approve condition-specific intervention templates.',
    fields: [
      field({ key: 'referralReason', label: 'Referral reason and precautions', kind: 'long_text', section: 'Referral', requiredToComplete: true }),
      field({ key: 'functionalBaseline', label: 'Functional baseline', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'outcomeMeasure', label: 'Outcome measure', kind: 'text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'baselineScore', label: 'Baseline score', kind: 'number', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'goals', label: 'Patient-centred measurable goals', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'interventionsDelivered', label: 'Interventions delivered', kind: 'long_text', section: 'Session', requiredToComplete: true }),
      field({ key: 'homeProgramme', label: 'Home programme / education', kind: 'long_text', section: 'Session', requiredToComplete: true }),
      field({ key: 'followUpScore', label: 'Follow-up score', kind: 'number', section: 'Outcome', requiredToComplete: true }),
      field({ key: 'disposition', label: 'Disposition', kind: 'select', section: 'Outcome', requiredToComplete: true, options: [{ value: 'continue', label: 'Continue therapy' }, { value: 'discharged_goals_met', label: 'Discharged — goals met' }, { value: 'discharged_other', label: 'Discharged — other' }, { value: 'referred', label: 'Referred onward' }] }),
    ],
  },
  {
    code: 'paediatrics', name: 'Paediatric clinic episode', departmentCodes: ['paediatrics'],
    summary: 'Age/weight context, ETAT danger signs, growth/nutrition, medicines safety and escalation.',
    evidenceLabel: 'WHO ETAT updated guideline', evidenceUrl: 'https://www.who.int/publications/i/item/9789241510219',
    safetyNote: 'Local paediatric protocols must govern age/weight dosing, oxygen, fluids, seizures and admission/referral thresholds.',
    fields: [
      field({ key: 'guardianName', label: 'Parent / guardian', kind: 'text', section: 'Context', requiredToComplete: true }),
      field({ key: 'ageMonths', label: 'Age', kind: 'number', section: 'Context', unit: 'months', requiredToComplete: true, min: 0 }),
      field({ key: 'weightKg', label: 'Current weight', kind: 'number', section: 'Context', unit: 'kg', requiredToComplete: true, min: 0 }),
      field({ key: 'etatDangerSigns', label: 'ETAT emergency / priority signs', kind: 'multi_select', section: 'Triage', requiredToComplete: true, options: [{ value: 'airway_breathing', label: 'Airway / breathing' }, { value: 'shock', label: 'Shock / impaired circulation' }, { value: 'coma_convulsion', label: 'Coma / convulsion' }, { value: 'severe_dehydration', label: 'Severe dehydration' }, { value: 'none', label: 'None identified' }] }),
      field({ key: 'dangerSignAction', label: 'Immediate action / not applicable', kind: 'long_text', section: 'Triage', requiredToComplete: true }),
      field({ key: 'growthNutritionAssessment', label: 'Growth and nutrition assessment', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'assessment', label: 'Clinical assessment', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'medicationWeightChecked', label: 'Weight/age checked for medication plan', kind: 'boolean', section: 'Plan', requiredToComplete: true }),
      field({ key: 'plan', label: 'Plan and caregiver advice', kind: 'long_text', section: 'Plan', requiredToComplete: true }),
      field({ key: 'disposition', label: 'Disposition', kind: 'select', section: 'Outcome', requiredToComplete: true, options: [{ value: 'home', label: 'Home' }, { value: 'admit', label: 'Admit' }, { value: 'emergency', label: 'Emergency care' }, { value: 'refer', label: 'Refer / transfer' }] }),
    ],
  },
  {
    code: 'obstetrics_gynaecology', name: 'Obstetrics & gynaecology episode', departmentCodes: ['obstetrics_gynaecology'],
    summary: 'Links antenatal, labour, delivery, postpartum/newborn and gynaecology care without duplicating existing registers.',
    evidenceLabel: 'WHO intrapartum care recommendations', evidenceUrl: 'https://www.who.int/publications/i/item/9789241550215',
    safetyNote: 'The maternity team must approve the locally adapted labour record, escalation thresholds, delivery/postpartum and newborn fields.',
    fields: [
      field({ key: 'carePhase', label: 'Care phase', kind: 'select', section: 'Context', requiredToComplete: true, options: [{ value: 'antenatal', label: 'Antenatal' }, { value: 'intrapartum', label: 'Labour / intrapartum' }, { value: 'delivery', label: 'Delivery' }, { value: 'postpartum', label: 'Postpartum' }, { value: 'gynaecology', label: 'Gynaecology' }] }),
      field({ key: 'ancRecordId', label: 'Linked ANC record / not applicable', kind: 'text', section: 'Context', requiredToComplete: true }),
      field({ key: 'gestationalAge', label: 'Gestational age / not applicable', kind: 'text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'maternalAssessment', label: 'Maternal assessment', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'fetalAssessment', label: 'Fetal assessment / not applicable', kind: 'long_text', section: 'Assessment', requiredToComplete: true }),
      field({ key: 'womanPreferences', label: 'Woman’s preferences, companion and consent', kind: 'long_text', section: 'Woman-centred care', requiredToComplete: true }),
      field({ key: 'labourRecordId', label: 'Linked labour-care record / not applicable', kind: 'text', section: 'Continuity', requiredToComplete: true }),
      field({ key: 'deliveryRecordId', label: 'Linked delivery/birth record / not applicable', kind: 'text', section: 'Continuity', requiredToComplete: true }),
      field({ key: 'newbornRecordId', label: 'Linked newborn record / not applicable', kind: 'text', section: 'Continuity', requiredToComplete: true }),
      field({ key: 'postpartumAssessment', label: 'Postpartum assessment / not applicable', kind: 'long_text', section: 'Outcome', requiredToComplete: true }),
      field({ key: 'planAndEscalation', label: 'Plan, warning signs and escalation', kind: 'long_text', section: 'Outcome', requiredToComplete: true }),
    ],
  },
] as const;

export function getSpecialtyPathway(code: SpecialtyPathwayCode): SpecialtyPathwayDefinition {
  const pathway = SPECIALTY_PATHWAYS.find((item) => item.code === code);
  if (!pathway) throw new Error(`Unknown specialty pathway: ${code}`);
  return pathway;
}
