'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api-fetch';
import { useApp } from '@/lib/context';
import type { AccountRequestDoc } from '@/lib/db-types';

export default function AccountRequestsPanel() {
  const { currentUser } = useApp(); const [requests, setRequests] = useState<AccountRequestDoc[]>([]); const [error, setError] = useState(''); const [credentials, setCredentials] = useState<{ username: string; temporaryPassword: string } | null>(null);
  async function load() { try { const r = await fetch('/api/account-requests', { cache: 'no-store' }); const b = await r.json(); if (!r.ok) { setError(b.error || 'Unable to load requests'); return; } setRequests(b.requests || []); } catch { setError('Unable to load requests. Check your connection and try again.'); } }
  // The request list is an external data source; load it once on mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  async function decide(req: AccountRequestDoc, action: 'approve' | 'reject') { try { const body: Record<string, unknown> = { requestId: req._id, action }; if (action === 'approve') { body.role = req.requestedRole; body.facilityId = req.facilityId; body.facilityName = req.facilityName; } else body.reason = 'Request was not approved'; const r = await apiFetch('/api/account-requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const b = await r.json(); if (!r.ok) { setError(b.error || 'Unable to update request'); return; } if (b.credentials) setCredentials(b.credentials); await load(); } catch { setError('Unable to update request. Check your connection and try again.'); } }
  if (!currentUser || !['super_admin', 'org_admin'].includes(currentUser.role)) return null;
  return <section className="p-6"><div className="flex items-center justify-between mb-5"><div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Account requests</h1><p className="text-sm text-[var(--text-muted)]">Review applicants before an account is provisioned.</p></div><span className="rounded-full bg-[var(--accent-light)] px-3 py-1 text-xs font-semibold">{requests.filter(r => r.status === 'pending').length} pending</span></div>{error && <p className="mb-4 text-sm text-red-600">{error}</p>}{credentials && <div className="mb-5 rounded-xl border border-green-200 bg-green-50 p-4 text-sm"><b>Credentials created — show these once:</b><div className="mt-2 font-mono">Username: {credentials.username}<br />Temporary password: {credentials.temporaryPassword}</div><button className="mt-2 text-xs underline" onClick={() => setCredentials(null)}>Dismiss</button></div>}<div className="space-y-3">{requests.map(r => <article key={r._id} className="rounded-xl border border-[var(--border-light)] bg-[var(--bg-card-solid)] p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-[var(--text-primary)]">{r.applicantName}</h2><p className="text-sm text-[var(--text-muted)]">{r.email} · {r.requestedRole.replace(/_/g, ' ')}</p><p className="text-xs text-[var(--text-muted)] mt-1">{r.organizationName || r.organizationId || 'New organization'} · submitted {new Date(r.createdAt).toLocaleString()}</p></div><span className="text-xs font-semibold uppercase">{r.status}</span></div>{r.message && <p className="mt-3 text-sm text-[var(--text-secondary)]">{r.message}</p>}{r.status === 'pending' && <div className="mt-4 flex gap-2"><button onClick={() => void decide(r, 'approve')} className="rounded-lg bg-[var(--accent-primary)] px-3 py-2 text-xs font-semibold text-white">Approve & create credentials</button><button onClick={() => void decide(r, 'reject')} className="rounded-lg border px-3 py-2 text-xs font-semibold">Reject</button></div>}</article>)}{requests.length === 0 && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-[var(--text-muted)]">No account requests yet.</p>}</div></section>;
}
