#!/usr/bin/env bash
# =============================================================================
# backup-couchdb.sh — host-side offsite CouchDB backup.
#
# Reads the latest dump produced by the in-container nightly dumper
# (scripts/dump-couchdb.sh, which writes to the `couchdb_backups` Docker
# volume), encrypts the snapshot with GPG against an asymmetric public key,
# and uploads the resulting object to S3 (or any S3-compatible store like
# Backblaze B2 with --endpoint-url).
#
# Usage:
#   ./scripts/backup-couchdb.sh
#
# Environment:
#   BACKUP_BUCKET           required. Bucket name (no s3:// prefix).
#   AWS_REGION              optional, default af-south-1.
#                           PHI residency: this MUST be af-south-1 unless
#                           you have explicit authorization to ship clinical
#                           data outside South Africa.
#   BACKUP_PUBKEY_PATH      optional, default /etc/tamamhealth/backup-pubkey.gpg
#   BACKUP_VOLUME_NAME      optional, default tamamhealth_couchdb_backups
#                           (the docker-compose project prefix is "tamamhealth")
#   AWS_ENDPOINT_URL        optional. Set for Backblaze B2 / MinIO / etc.
#                           e.g. https://s3.eu-central-003.backblazeb2.com
#   BACKUP_HTTP_PUT_URL     optional. If set AND `aws` CLI is missing, the
#                           script falls back to a plain HTTP PUT (signed URL
#                           or basic-auth — generated by the operator).
#
# Exits non-zero on any failure. Logs to syslog via `logger`.
# =============================================================================
set -euo pipefail

usage() {
  sed -n '3,28p' "$0" | sed 's/^# \{0,1\}//'
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage; exit 0
fi

LOG_TAG="tamamhealth-backup-couchdb"
log()  { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; logger -t "$LOG_TAG" "$*" || true; }
die()  { log "ERROR: $*"; exit 1; }

: "${BACKUP_BUCKET:?BACKUP_BUCKET is required (no s3:// prefix)}"
: "${AWS_REGION:=af-south-1}"
: "${BACKUP_PUBKEY_PATH:=/etc/tamamhealth/backup-pubkey.gpg}"
: "${BACKUP_VOLUME_NAME:=tamamhealth_couchdb_backups}"

command -v gpg     >/dev/null 2>&1 || die "gpg not installed"
command -v docker  >/dev/null 2>&1 || die "docker not installed"
command -v tar     >/dev/null 2>&1 || die "tar not installed"
[ -r "$BACKUP_PUBKEY_PATH" ] || die "backup pubkey not readable at $BACKUP_PUBKEY_PATH"

# Locate the host path of the docker volume.
VOL_PATH=$(docker volume inspect --format '{{.Mountpoint}}' "$BACKUP_VOLUME_NAME" 2>/dev/null || true)
[ -n "$VOL_PATH" ] || die "docker volume '$BACKUP_VOLUME_NAME' not found"
[ -d "$VOL_PATH" ] || die "volume mountpoint '$VOL_PATH' does not exist"

STAMP_DAY=$(date -u +%Y/%m/%d)
STAMP_HM=$(date -u +%H%M)
HOST=$(hostname -s)
OBJECT_KEY="${STAMP_DAY}/couchdb-${HOST}-${STAMP_HM}.tar.gz.gpg"

WORK=$(mktemp -d -t backup-couchdb.XXXXXX)
trap 'rm -rf "$WORK"' EXIT

ARCHIVE="${WORK}/snapshot.tar.gz"
ENCRYPTED="${WORK}/snapshot.tar.gz.gpg"

log "snapshotting volume $BACKUP_VOLUME_NAME ($VOL_PATH) -> $ARCHIVE"
# We tar the entire volume contents — it already contains the per-day
# tamamhealth_*.json.gz dumps written by the in-container dumper.
tar --warning=no-file-changed -czf "$ARCHIVE" -C "$VOL_PATH" . || die "tar failed"

ARCHIVE_BYTES=$(wc -c < "$ARCHIVE" | tr -d ' ')
[ "$ARCHIVE_BYTES" -gt 0 ] || die "snapshot archive is empty"
log "snapshot OK ($ARCHIVE_BYTES bytes)"

# Import the recipient pubkey into a throwaway GNUPGHOME so we never touch
# whatever is in the operator's $HOME/.gnupg.
export GNUPGHOME="${WORK}/gnupg"
mkdir -p "$GNUPGHOME"
chmod 700 "$GNUPGHOME"
gpg --batch --quiet --import "$BACKUP_PUBKEY_PATH" || die "gpg import failed"

# Encrypt with --trust-model always so the operator does not have to sign
# the public key first. The pubkey is the operator's own backup key — they
# already trust it implicitly by virtue of placing it in /etc/tamamhealth.
RECIPIENT=$(gpg --list-keys --with-colons | awk -F: '/^uid:/ {print $10; exit}')
[ -n "$RECIPIENT" ] || die "could not extract recipient from pubkey"

log "encrypting -> $ENCRYPTED (recipient: $RECIPIENT)"
gpg --batch --yes --trust-model always \
    --output "$ENCRYPTED" \
    --encrypt --recipient "$RECIPIENT" \
    "$ARCHIVE" \
  || die "gpg encrypt failed"

[ -s "$ENCRYPTED" ] || die "encrypted file is empty"

# Upload. Prefer aws CLI; fall back to curl PUT.
S3_URI="s3://${BACKUP_BUCKET}/${OBJECT_KEY}"
log "uploading -> $S3_URI"

if command -v aws >/dev/null 2>&1; then
  AWS_ARGS=(--region "$AWS_REGION")
  if [ -n "${AWS_ENDPOINT_URL:-}" ]; then
    AWS_ARGS+=(--endpoint-url "$AWS_ENDPOINT_URL")
  fi
  aws "${AWS_ARGS[@]}" s3 cp \
      --only-show-errors \
      --sse AES256 \
      "$ENCRYPTED" "$S3_URI" \
    || die "aws s3 cp failed"

  # Verify by HEADing the object — `aws s3api head-object` returns metadata
  # and exits non-zero if the object isn't there.
  aws "${AWS_ARGS[@]}" s3api head-object \
      --bucket "$BACKUP_BUCKET" \
      --key   "$OBJECT_KEY" \
      >/dev/null \
    || die "post-upload HEAD failed; object did NOT land"
else
  log "aws CLI not present; falling back to HTTP PUT"
  : "${BACKUP_HTTP_PUT_URL:?aws CLI missing AND BACKUP_HTTP_PUT_URL not set; cannot upload}"
  command -v curl >/dev/null 2>&1 || die "neither aws nor curl available"
  HTTP_CODE=$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' \
      --upload-file "$ENCRYPTED" \
      "${BACKUP_HTTP_PUT_URL}/${OBJECT_KEY}" \
    || true)
  case "$HTTP_CODE" in
    200|201|204) log "HTTP PUT OK ($HTTP_CODE)" ;;
    *) die "HTTP PUT returned $HTTP_CODE" ;;
  esac
  # Verify with HEAD
  HEAD_CODE=$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' \
      --head "${BACKUP_HTTP_PUT_URL}/${OBJECT_KEY}" \
    || true)
  case "$HEAD_CODE" in
    200) log "HEAD OK" ;;
    *) die "post-upload HEAD returned $HEAD_CODE" ;;
  esac
fi

log "couchdb backup complete: $S3_URI"

# ── Tell the platform the backup happened ────────────────────────────────────
# Without this the loop is open: backups run, nothing records them, and the
# Risk Center carries a HIGH "No backup on record" that no successful backup can
# clear. Reported only HERE — after the upload has been verified with HEAD — so
# what is recorded is a backup that actually landed, never one that was merely
# attempted.
#
# Signed the same way the CouchDB webhook is (see lib/sync-auth.ts): timestamp,
# nonce, method, path and body joined by newlines, HMAC-SHA256 under
# COUCHDB_WEBHOOK_SECRET. Best-effort — a reporting failure must not fail a
# backup that already succeeded, so it warns and exits 0.
if [ -n "${TAMAM_APP_URL:-}" ] && [ -n "${COUCHDB_WEBHOOK_SECRET:-}" ]; then
  REPORT_PATH="/api/admin/backup"
  REPORT_BODY="{\"completedAt\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}"
  REPORT_TS=$(date -u +%s)
  REPORT_NONCE=$(uuidgen 2>/dev/null | tr '[:upper:]' '[:lower:]' \
    || python3 -c 'import uuid; print(uuid.uuid4())')
  REPORT_SIG="sha256=$(printf '%s\n%s\nPOST\n%s\n%s' \
      "$REPORT_TS" "$REPORT_NONCE" "$REPORT_PATH" "$REPORT_BODY" \
    | openssl dgst -sha256 -hmac "$COUCHDB_WEBHOOK_SECRET" -r | cut -d' ' -f1)"
  REPORT_CODE=$(curl --silent --show-error --output /dev/null --write-out '%{http_code}' \
      --max-time 15 \
      --request POST "${TAMAM_APP_URL}${REPORT_PATH}" \
      --header 'Content-Type: application/json' \
      --header "x-tamamhealth-signature: ${REPORT_SIG}" \
      --header "x-tamamhealth-timestamp: ${REPORT_TS}" \
      --header "x-tamamhealth-nonce: ${REPORT_NONCE}" \
      --data "$REPORT_BODY" \
    || true)
  case "$REPORT_CODE" in
    200) log "reported backup to the platform" ;;
    *)   log "WARNING: backup ran but reporting it returned ${REPORT_CODE:-no response};" \
             "the Risk Center will still show no backup on record" ;;
  esac
else
  log "TAMAM_APP_URL or COUCHDB_WEBHOOK_SECRET unset — backup NOT reported to the platform;" \
      "the Risk Center will show no backup on record"
fi
